//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.07.30 at 03:23:09 PM MSK
//


package ru.sberbank.syncserver2.service.sql.query;

import ru.sberbank.syncserver2.service.sql.SQLService;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;



/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stored-procedure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="arguments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="argument" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "storedProcedure",
    "sqlTemplate",
    "arguments",
    "datasetMetaData",
    "textSubstitutes",
    "provider",
    "alphaWebHost",
    "alphaDbHost",
    "service"
})
@XmlRootElement(name = "request")
public class OnlineRequest {

    /**
     * SIGMA database provider
     */
    @XmlElement
    protected String provider;

    /**
     * ALPHA service backend
     */
    @XmlElement
    protected String service;

    @XmlElement(name = "alpha-web-host", required = false)
    protected String alphaWebHost;

    @XmlElement(name = "alpha-db-host", required = false)
    protected String alphaDbHost;

    @XmlElement(name = "stored-procedure", required = false)
    protected String storedProcedure;

    @XmlElement(name = "sql-template", required = false)
    protected String sqlTemplate;

    @XmlElement
    protected OnlineRequest.Arguments arguments;

    @XmlElement(name = "Fields")
    private DatasetMetaData datasetMetaData;

    @XmlElement(name = "TextSubstitutes")
    protected TextSubstitutes textSubstitutes;

    public TextSubstitutes getTextSubstitutes() {
        return textSubstitutes;
    }

    public void setTextSubstitutes(TextSubstitutes value) {
        this.textSubstitutes = value;
    }

	@XmlTransient
    private String userEmail;

    @XmlTransient
    private String userIpAddress;

    public String getUserEmail() {
		return userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserIpAddress() {
		return userIpAddress;
	}

	public void setUserIpAddress(String userIpAddress) {
		this.userIpAddress = userIpAddress;
	}

    public DatasetMetaData getDatasetMetaData() {
        return datasetMetaData;
    }

    public void setDatasetMetaData(DatasetMetaData fields) {
        this.datasetMetaData = fields;
    }

    /**
     * Gets the value of the storedProcedure property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStoredProcedure() {
        return storedProcedure;
    }

    /**
     * Sets the value of the storedProcedure property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStoredProcedure(String value) {
        this.storedProcedure = value;
    }

    /**
     * Gets the value of the arguments property.
     *
     * @return
     *     possible object is
     *     {@link OnlineRequest.Arguments }
     *
     */
    public OnlineRequest.Arguments getArguments() {
        return arguments;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getService() {
        return service;
    }

    public void setService(String service) {
        this.service = service;
    }

    public String getAlphaWebHost() {
        return alphaWebHost;
    }

    public void setAlphaWebHost(String alphaWebHost) {
        this.alphaWebHost = alphaWebHost;
    }

    public String getAlphaDbHost() {
        return alphaDbHost;
    }

    public void setAlphaDbHost(String alphaDbHost) {
        this.alphaDbHost = alphaDbHost;
    }

    public String getSqlTemplate() {
        return sqlTemplate;
    }

    public void setSqlTemplate(String sqlTemplate) {
        this.sqlTemplate = sqlTemplate;
    }

    /**
     * Sets the value of the arguments property.
     *
     * @param value
     *     allowed object is
     *     {@link OnlineRequest.Arguments }
     *
     */
    public void setArguments(OnlineRequest.Arguments value) {
        this.arguments = value;
    }



    @Override
	public String toString() {
		return "OnlineRequest {provider=" + provider + ", service=" + service + ", storedProcedure=" + storedProcedure
				+ ", arguments=" + arguments + ", datasetMetaData=" + datasetMetaData + ", userEmail=" + userEmail
				+ ", userIpAddress=" + userIpAddress + "}";
	}

    public void convertToNewSigma(){
        //1. Converting to sql-template
        //this.sqlTemplate = storedProcedure;
        //this.storedProcedure = null;

        //2. Converting service
        this.alphaWebHost = service;
        this.alphaDbHost = service;
        this.service = null;
        this.provider = SQLService.PROVIDER_DISPATCHER;
    }

    public void convertToPassportSigma(){
        convertToNewSigma();
        this.sqlTemplate = storedProcedure;
        this.storedProcedure = null;
    }

    public void convertToOldAlpha(){
        //this.storedProcedure = this.sqlTemplate;
        //this.sqlTemplate = null;

        this.service = alphaDbHost;
        this.alphaDbHost = null;
        this.alphaWebHost = null;
    }

    public void convertToPassportAlpha(){
        convertToOldAlpha();
        this.storedProcedure = this.sqlTemplate;
        this.sqlTemplate = null;
    }

    public void convertToTempAlpha(){
        if(!SQLService.PROVIDER_DISPATCHER.equalsIgnoreCase(provider)){
            this.service = provider;
            this.provider = SQLService.PROVIDER_DISPATCHER;
        }
    }

    public void convertToTempSigma(){
        this.provider = service;
    }

    public void trim(){
        if(provider!=null){
            provider = provider.trim();
        }
        if(service!=null){
            service = service.trim();
        }
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="argument" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "argument"
    })
    public static class Arguments {

        protected List<OnlineRequest.Arguments.Argument> argument;


        /**
         * Gets the value of the argument property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the argument property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getArgument().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OnlineRequest.Arguments.Argument }
         *
         *
         */
        public List<OnlineRequest.Arguments.Argument> getArgument() {
            if (argument == null) {
                argument = new ArrayList<OnlineRequest.Arguments.Argument>();
            }
            return this.argument;
        }

        public void  setArgument(List<OnlineRequest.Arguments.Argument> argument) {
            if (argument == null) {
                argument = new ArrayList<OnlineRequest.Arguments.Argument>();
            }
            this.argument = argument;
        }

        @Override
        public String toString() {
            return "Arguments [argument=" + argument + "]";
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "index",
            "type",
            "value"
        })
        public static class Argument {

            protected int index;

            @XmlElement(required = true)
            protected FieldType type;

            @XmlElement(required = true)
            protected String value;

            public Argument() {

            }

            public Argument(int index, FieldType type, String value) {
				this.index = index;
				this.type = type;
                if (type == FieldType.STRING && value == null) {
                    this.value = "";
                } else {
				    this.value = value;
                }
			}

			/**
             * Gets the value of the index property.
             *
             */
            public int getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             *
             */
            public void setIndex(int value) {
                this.index = value;
            }

            /**
             * Gets the value of the type property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public FieldType getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setType(FieldType value) {
                this.type = value;
            }

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            @Override
            public String toString() {
                return "Argument [index=" + index + ", type=" + type
                        + ", value=" + value + "]";
            }

        }
    }
}
