DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.CHANGE_COMMENT_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_DATA_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_DATA_CARD_DETAIL_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_DATA_FA_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_DATA_SEARCH_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DETAILCARD_TEMPLATE_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.ENTERPOINT_DATA_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.GET_COMMENT_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.INDICATOR_FACT_PLAN_FORECAST_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.INDICATOR_HISTORY_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.LAST_DATE_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.PERSONAL_CARD_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.REPORT_DATA_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.RESOURCE_IMAGE_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.UPDATE_NOTIFICATION_READ_STATUS_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.USER_NOTIFICATION_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_CUSTOMIZE_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.COMMENT_HISTORY_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.COMMENT_NO_READ_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.COMMENT_SET_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.EMPLOYEE_LIST_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.PUSH_NOTIFICATION_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.INDICATOR_DESCRIPTION_SUBST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_COMMENTS_SUBST'
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.CHANGE_COMMENT_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_changeComment] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getDashBoard] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_DATA_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getDashBoardData] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_DATA_CARD_DETAIL_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getDashBoardDataCardDetail] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_DATA_FA_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getDashBoardDataFA] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_DATA_SEARCH_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getDashBoardDataSearch] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DETAILCARD_TEMPLATE_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getDetailCardTemplate] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.ENTERPOINT_DATA_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getEnterPointData] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.GET_COMMENT_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getComment] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.INDICATOR_FACT_PLAN_FORECAST_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getIndicatorFactPlanForecast] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.INDICATOR_HISTORY_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getIndicatorHistory] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.LAST_DATE_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getLastModifyDate] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.PERSONAL_CARD_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getEmployeePersonalCard] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.REPORT_DATA_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getReportDataByID] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.RESOURCE_IMAGE_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getResouceImageByID] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.UPDATE_NOTIFICATION_READ_STATUS_SUBST', 'EXEC [${INAV_2_0_DB}].[dbo].UPDATE_NOTIFICATION_READ_STATUS ?, ?, ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.USER_NOTIFICATION_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getUserNotification] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_CUSTOMIZE_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_putDashBoardSettings] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.PUSH_NOTIFICATION_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getPushNotification] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.EMPLOYEE_LIST_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getEmployeeList] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.COMMENT_HISTORY_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getHistoryComment] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.COMMENT_SET_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_setComment] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.COMMENT_NO_READ_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getCommentNoRead] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.INDICATOR_DESCRIPTION_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getIndicatorDescriptionByID] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_COMMENTS_SUBST', 'EXEC [${INAV_2_0_DB}].[UI].[mobile_getCommentsCountDBDD] ?')
GO

DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.CHANGE_COMMENT'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_DATA'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_DATA_CARD_DETAIL'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_DATA_FA'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DASHBOARD_DATA_SEARCH'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.DETAILCARD_TEMPLATE'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.ENTERPOINT_DATA'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.GET_COMMENT'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.INDICATOR_FACT_PLAN_FORECAST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.INDICATOR_HISTORY'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.LAST_DATE'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.PERSONAL_CARD'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.REPORT_DATA'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.RESOURCE_IMAGE'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.UPDATE_NOTIFICATION_READ_STATUS'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.USER_NOTIFICATION'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.COMMENT_HISTORY'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.COMMENT_NO_READ'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.COMMENT_SET'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.EMPLOYEE_LIST'
GO
DELETE FROM SQL_TEMPLATES_MOBILE WHERE TEMPLATE_CODE = 'INAV_2_0.PUSH_NOTIFICATION'
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.CHANGE_COMMENT', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_changeComment] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getDashBoard] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_DATA', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getDashBoardData] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_DATA_CARD_DETAIL', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getDashBoardDataCardDetail] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_DATA_FA', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getDashBoardDataFA] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DASHBOARD_DATA_SEARCH', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getDashBoardDataSearch] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.DETAILCARD_TEMPLATE', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getDetailCardTemplate] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.ENTERPOINT_DATA', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getEnterPointData] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.GET_COMMENT', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getComment] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.INDICATOR_FACT_PLAN_FORECAST', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getIndicatorFactPlanForecast] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.INDICATOR_HISTORY', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getIndicatorHistory] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.LAST_DATE', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getLastModifyDate] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.PERSONAL_CARD', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getEmployeePersonalCard] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.REPORT_DATA', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getReportDataByID] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.RESOURCE_IMAGE', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getResouceImageByID] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.UPDATE_NOTIFICATION_READ_STATUS', 'EXEC [MIS_NAVIGATOR_KPI_20].[dbo].UPDATE_NOTIFICATION_READ_STATUS ?, ?, ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.USER_NOTIFICATION', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getUserNotification] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.PUSH_NOTIFICATION', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getPushNotification] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.EMPLOYEE_LIST', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getEmployeeList] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.COMMENT_HISTORY', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getHistoryComment] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.COMMENT_SET', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_setComment] ?')
GO
INSERT INTO SQL_TEMPLATES_MOBILE ([TEMPLATE_CODE] , [TEMPLATE_SQL]) VALUES ('INAV_2_0.COMMENT_NO_READ', 'EXEC [MIS_NAVIGATOR_KPI_20].[UI].[mobile_getCommentNoRead] ?')
GO