delete from SUBST_DICT where APP_CODE = 'INAV_2_0'
GO	
insert into SUBST_DICT(SUBST_CODE, SUBST_VALUE, APP_CODE) VALUES ('INAV_2_0.DB_MAIN', 'MIS_NAVIGATOR_KPI_20',    'INAV_2_0')
GO
insert into SUBST_DICT(SUBST_CODE, SUBST_VALUE, APP_CODE) VALUES ('INAV_2_0.DB_CB',   'MIS_NAVIGATOR_KPI_20_CB', 'INAV_2_0')
GO
insert into SUBST_DICT(SUBST_CODE, SUBST_VALUE, APP_CODE) VALUES ('INAV_2_0.DB_DVLP',   'MIS_NAVIGATOR_KPI_20_DVLP', 'INAV_2_0')
GO