if object_id('GENERATOR_GROUP_USERS') is not null DROP TABLE GENERATOR_GROUP_USERS
go
if object_id('ADD_USER_TO_DRAFT_GROUP') is not null DROP PROCEDURE ADD_USER_TO_DRAFT_GROUP
go
if object_id('GET_USER_EMAILS') is not null DROP PROCEDURE GET_USER_EMAILS
go
if object_id('SP_CHANGE_APP_FILE_STATUS') is not null DROP PROCEDURE SP_CHANGE_APP_FILE_STATUS
go
if object_id('SP_PUBLISH_CURRENT_DRAFT') is not null DROP PROCEDURE SP_PUBLISH_CURRENT_DRAFT
go
if object_id('GET_GENERATOR_USER_GROUPS_FOR_DRAFT') is not null DROP PROCEDURE GET_GENERATOR_USER_GROUPS_FOR_DRAFT
go
if object_id('REMOVE_USER_FROM_DRAFT_GROUP') is not null DROP PROCEDURE REMOVE_USER_FROM_DRAFT_GROUP
go
if object_id('SP_GET_FILE_STATUSES') is not null DROP PROCEDURE SP_GET_FILE_STATUSES
go
if object_id('SP_GET_GENERATOR_USER_GROUPS_FOR_DRAFT') is not null DROP PROCEDURE SP_GET_GENERATOR_USER_GROUPS_FOR_DRAFT
go
if object_id('GET_FILE_DRAFT_STATUS') is not null DROP PROCEDURE GET_FILE_DRAFT_STATUS
go
if object_id('SP_DELETE_CURRENT_DRAFT') is not null DROP PROCEDURE SP_DELETE_CURRENT_DRAFT
go

-- table for user groups
CREATE TABLE GENERATOR_GROUP_USERS (
	APP_ID		VARCHAR(256),
	EMAIL		VARCHAR(256),
	GROUP_CODE	VARCHAR(256) -- now, we have only 1 group - draft(id = 1)
)
GO

CREATE PROCEDURE REMOVE_USER_FROM_DRAFT_GROUP
	@appId VARCHAR(256),
	@email VARCHAR(256)
AS
	DELETE FROM  GENERATOR_GROUP_USERS WHERE 
	APP_ID = @appID and EMAIL = @email
GO

-- add new user to content controller
CREATE PROCEDURE ADD_USER_TO_DRAFT_GROUP
	@appId VARCHAR(256),
	@email VARCHAR(256)
AS
	exec REMOVE_USER_FROM_DRAFT_GROUP @appId,@email
	INSERT INTO  GENERATOR_GROUP_USERS(APP_ID,EMAIL,GROUP_CODE)
	SELECT UPPER(@appId),UPPER(@email),'SINGLE_DRAFT_GROUP'
GO

-- get user emails
CREATE PROCEDURE GET_USER_EMAILS
AS
	SELECT DISTINCT EMAIL FROM  GENERATOR_GROUP_USERS
GO

-- change app file status
CREATE PROCEDURE SP_CHANGE_APP_FILE_STATUS
	@app varchar(256),
	@fileId varchar(256),
	@published_file_md5 varchar(256),
	@draft_file_md5 varchar(256)
AS
	if @published_file_md5 is not null
		UPDATE SYNC_CACHE_STATIC_FILES set PUBLISHED_FILE_MD5 = @published_file_md5 where (APP_CODE = @app OR @app IS NULL or @app = '') and  (FILE_ID = @fileId OR FILE_NAME = @fileId)

	if @draft_file_md5 is not null
		UPDATE SYNC_CACHE_STATIC_FILES set DRAFT_FILE_MD5 = @draft_file_md5 where (APP_CODE = @app OR @app IS NULL or @app = '') and  (FILE_ID = @fileId OR FILE_NAME = @fileId)
	commit;
GO

-- publish current draft
CREATE PROCEDURE SP_PUBLISH_CURRENT_DRAFT
	@app varchar(256),
	@fileId varchar(256)
AS
	UPDATE SYNC_CACHE_STATIC_FILES set PUBLISHED_FILE_MD5 = DRAFT_FILE_MD5 WHERE APP_CODE = @app and (FILE_ID = @fileId OR FILE_NAME = @fileId)
	UPDATE SYNC_CACHE_STATIC_FILES set DRAFT_FILE_MD5 = NULL WHERE  APP_CODE = @app and (FILE_ID = @fileId OR FILE_NAME = @fileId)
GO

-- delete current draft
CREATE PROCEDURE SP_DELETE_CURRENT_DRAFT
	@app varchar(256),
	@fileId varchar(256)
AS
	UPDATE SYNC_CACHE_STATIC_FILES set DRAFT_FILE_MD5 = NULL WHERE  APP_CODE = @app and (FILE_ID = @fileId OR FILE_NAME = @fileId)
GO


CREATE PROCEDURE SP_GET_FILE_STATUSES 
AS
	SELECT SYNC_CACHE_FILE_ID, APP_CODE, FILE_ID, PUBLISHED_FILE_MD5, DRAFT_FILE_MD5,GENERATION_MODE FROM SYNC_CACHE_STATIC_FILES
GO

CREATE PROCEDURE SP_GET_GENERATOR_USER_GROUPS_FOR_DRAFT
AS
	SELECT APP_ID, EMAIL FROM GENERATOR_GROUP_USERS WHERE GROUP_CODE = 'SINGLE_DRAFT_GROUP'
GO


CREATE PROCEDURE GET_FILE_DRAFT_STATUS
	@app varchar(256),
	@fileId varchar(256)
AS
	SELECT GENERATION_MODE FROM SYNC_CACHE_STATIC_FILES WHERE (UPPER(APP_CODE)=UPPER(@app) OR (@app IS NULL) or @app = '') AND 
	(UPPER(FILE_NAME)=UPPER(@fileId) OR  UPPER(FILE_ID)=UPPER(@fileId))
GO