IF OBJECT_ID('SYNC_MAINTENANCE') IS NOT NULL DROP TABLE SYNC_MAINTENANCE
GO
IF OBJECT_ID('UPDATE_MAINTENANCE') IS NOT NULL DROP PROCEDURE UPDATE_MAINTENANCE
GO

CREATE TABLE SYNC_MAINTENANCE(
   ACTIVE			BIT					NOT NULL,
   MESSAGE_TEXT		nVARCHAR(max)		NULL,
   EMAILS			VARCHAR(max)		NULL,
   DATE				DATETIME			NOT NULL
)
INSERT INTO SYNC_MAINTENANCE VALUES(0, NULL, NULL, GETDATE())
GO

CREATE PROCEDURE UPDATE_MAINTENANCE
   @active	BIT,
   @msg		nVARCHAR(max),
   @emails	VARCHAR(max)
AS
	UPDATE SYNC_MAINTENANCE SET ACTIVE = @active, MESSAGE_TEXT = @msg, EMAILS = @emails, DATE = getDate()
GO

