set nocount
on
if object_id('SYNC_PUSH_NOTIFICATIONS') is not null DROP TABLE SYNC_PUSH_NOTIFICATIONS
GO
if object_id('SYNC_PUSH_NOTIFICATIONS_ARCHIVE') is not null DROP TABLE SYNC_PUSH_NOTIFICATIONS_ARCHIVE
GO
if object_id('SEND_NOTIFICATION') is not null DROP PROCEDURE SEND_NOTIFICATION
GO
if object_id('SELECT_PUSH_NOTIFICATIONS') is not null DROP PROCEDURE SELECT_PUSH_NOTIFICATIONS
GO
if object_id('INSERT_PUSH_NOTIFICATION') is not null DROP PROCEDURE INSERT_PUSH_NOTIFICATION
GO
if object_id('SYNC_PUSH_NOTIFICATIONS_CLIENTS') is not null DROP TABLE SYNC_PUSH_NOTIFICATIONS_CLIENTS
GO
if object_id('SYNC_PUSH_NOTIFICATIONS2CLIENT') is not null DROP TABLE SYNC_PUSH_NOTIFICATIONS2CLIENT
GO
if object_id('GET_OS_CODES') is not null DROP PROCEDURE GET_OS_CODES
GO
if object_id('INSERT_PUSH_NOTIFICATIONS_CLIENT') is not null DROP PROCEDURE INSERT_PUSH_NOTIFICATIONS_CLIENT
GO
if object_id('GET_APPLICATIONS') is not null DROP PROCEDURE GET_APPLICATIONS
GO
if object_id('GET_APPLICATION_VERSIONS') is not null DROP PROCEDURE GET_APPLICATION_VERSIONS
GO
if object_id('GET_EMAILS') is not null DROP PROCEDURE GET_EMAILS
GO
if object_id('GET_DEVICES') is not null DROP PROCEDURE GET_DEVICES
GO
if object_id('SELECT_NOTIFICATION_CLIENTS') is not null DROP PROCEDURE SELECT_NOTIFICATION_CLIENTS
GO
if object_id('ADD_CLIENTS_TO_NOTIFICATION') is not null DROP PROCEDURE ADD_CLIENTS_TO_NOTIFICATION
GO
if object_id('GET_CLIENTS_BY_NOTIFICATION') is not null DROP PROCEDURE GET_CLIENTS_BY_NOTIFICATION
GO
if object_id('SET_NOTIFICATION_2_CLIENT_STATUS') is not null DROP PROCEDURE SET_NOTIFICATION_2_CLIENT_STATUS
GO
if object_id('GET_NOTIFICATIONS') is not null DROP PROCEDURE GET_NOTIFICATIONS
GO


CREATE TABLE SYNC_PUSH_NOTIFICATIONS(
  SYNC_PN_ID     		  INT IDENTITY(1,1) PRIMARY KEY,
  SYNC_PNC_ID			  INT,
  SYNC_PN_MESSAGE_TEXT	  VARCHAR(512) NOT NULL,
  SYNC_PN_PARAMETERS	  VARCHAR(512),
  SYNC_PN_BADGE_NUMBER	  INT NOT NULL,
  SYNC_PN_SOUND_NAME	  VARCHAR(256) NOT NULL,
  SYNC_PN_EVENT_CODE	  VARCHAR(20) NOT NULL,
  SYNC_PN_PUSH_DATE	 	  DATETIME NOT NULL,
  SYNC_PN_LOCK_TIME	 	  DATETIME,
  SYNC_PN_NOTIFY_TIME 	  DATETIME
)
GO

CREATE TABLE SYNC_PUSH_NOTIFICATIONS_ARCHIVE(
  SYNC_PNA_ID     		  INT NOT NULL,
  SYNC_PNC_ID			  INT,
  SYNC_PNA_MESSAGE_TEXT	  VARCHAR(512) NOT NULL,
  SYNC_PN_PARAMETERS	  VARCHAR(512),
  SYNC_PNA_BADGE_NUMBER	  INT NOT NULL,
  SYNC_PNA_SOUND_NAME	  VARCHAR(256) NOT NULL,
  SYNC_PNA_EVENT_CODE	  VARCHAR(20) NOT NULL,
  SYNC_PNA_PUSH_DATE	 	  DATETIME NOT NULL,
  SYNC_PNA_LOCK_TIME	 	  DATETIME,
  SYNC_PNA_NOTIFY_TIME 	  DATETIME
)
GO

CREATE TABLE SYNC_PUSH_NOTIFICATIONS_CLIENTS (
	SYNC_PNC_ID						INT IDENTITY(1,1) PRIMARY KEY,
	SYNC_PNC_OS_CODE	 			VARCHAR(256) NOT NULL,
	SYNC_PNC_APPLICATION_CODE	 	VARCHAR(256) NOT NULL,
	SYNC_PNC_APPLICATION_VERSION	VARCHAR(256) NOT NULL,
	SYNC_PNC_EMAIL 		 			VARCHAR(512),
	SYNC_PNC_DEVICE_NAME 			VARCHAR(512),
	SYNC_PNC_DEVICE_CODE 			VARCHAR(512),
	SYNC_PNC_APPLE_TOKEN 			VARCHAR(512)
)
GO

CREATE TABLE SYNC_PUSH_NOTIFICATIONS2CLIENT (
	SYNC_PN2C_ID					INT IDENTITY(1,1) PRIMARY KEY,
	SYNC_PN_ID						INT NOT NULL,
	SYNC_PNC_ID						INT NOT NULL,
	SYNC_PNC_STATUS					INT NOT NULL DEFAULT 0
)
GO


CREATE PROCEDURE INSERT_PUSH_NOTIFICATION
  @message_text  		VARCHAR(512),
  @bange_number			INT,
  @sound_name  			VARCHAR(256),
  @push_date			DATETIME,
  @event_code			VARCHAR(20)
AS
	 SET NOCOUNT ON
	 INSERT INTO SYNC_PUSH_NOTIFICATIONS(SYNC_PN_MESSAGE_TEXT,SYNC_PN_BADGE_NUMBER,SYNC_PN_SOUND_NAME,SYNC_PN_EVENT_CODE,SYNC_PN_PUSH_DATE) 
	 values  (@message_text,@bange_number,@sound_name,@event_code,@push_date)
	 select @@IDENTITY ID
GO

CREATE PROCEDURE ADD_CLIENTS_TO_NOTIFICATION
	@notification_id int,
	@notification_client_id int
AS
 	INSERT INTO SYNC_PUSH_NOTIFICATIONS2CLIENT(SYNC_PN_ID,SYNC_PNC_ID)
	SELECT @notification_id,@notification_client_id
GO

CREATE PROCEDURE GET_CLIENTS_BY_NOTIFICATION
	@notification_id int,
	@from int,
	@length int
AS
if (@length>=0) begin
SELECT * FROM
(
	SELECT  [RANK] = ROW_NUMBER() OVER (ORDER BY C.SYNC_PNC_ID),
			C.SYNC_PNC_ID, 
			C.SYNC_PNC_OS_CODE, 
			C.SYNC_PNC_APPLICATION_CODE, 
			C.SYNC_PNC_APPLICATION_VERSION, 
			C.SYNC_PNC_EMAIL, 
			C.SYNC_PNC_DEVICE_NAME, 
			C.SYNC_PNC_APPLE_TOKEN,
			N2C.SYNC_PNC_STATUS
	FROM
		SYNC_PUSH_NOTIFICATIONS_CLIENTS C,
		SYNC_PUSH_NOTIFICATIONS2CLIENT N2C
	WHERE 
		C.SYNC_PNC_ID = N2C.SYNC_PNC_ID AND
		N2C.SYNC_PN_ID = @notification_id
) A	WHERE A.[RANK] BETWEEN @from+1 AND @from+@length	
end else begin
	SELECT  
			C.SYNC_PNC_ID, 
			C.SYNC_PNC_OS_CODE, 
			C.SYNC_PNC_APPLICATION_CODE, 
			C.SYNC_PNC_APPLICATION_VERSION, 
			C.SYNC_PNC_EMAIL, 
			C.SYNC_PNC_DEVICE_NAME, 
			C.SYNC_PNC_APPLE_TOKEN,
			N2C.SYNC_PNC_STATUS
	FROM
		SYNC_PUSH_NOTIFICATIONS_CLIENTS C,
		SYNC_PUSH_NOTIFICATIONS2CLIENT N2C
	WHERE 
		C.SYNC_PNC_ID = N2C.SYNC_PNC_ID AND
		N2C.SYNC_PN_ID = @notification_id
end
GO


CREATE PROCEDURE SELECT_NOTIFICATION_CLIENTS
	@os_code  				VARCHAR(256),
	@application_code		VARCHAR(256),
	@application_version	VARCHAR(256),
	@emails					VARCHAR(256),
	@devices				VARCHAR(256)
AS
    SET NOCOUNT ON;
    declare @sql nvarchar(2000)

    set @sql = '
		 SELECT 
			SYNC_PNC_ID, 
			SYNC_PNC_OS_CODE, 
			SYNC_PNC_APPLICATION_CODE, 
			SYNC_PNC_APPLICATION_VERSION, 
			SYNC_PNC_EMAIL, 
			SYNC_PNC_DEVICE_NAME, 
			SYNC_PNC_APPLE_TOKEN
		 FROM
		   SYNC_PUSH_NOTIFICATIONS_CLIENTS where (1 = 1)'
	if (@os_code is not null and @os_code != '') 
		set @sql = @sql + 'AND SYNC_PNC_OS_CODE IN (' + @os_code + ')'
	if (@application_code is not null and @application_code != '') 
		set @sql = @sql + 'AND SYNC_PNC_APPLICATION_CODE IN (' + @application_code + ')'
	if (@application_version is not null and @application_version != '') 
		set @sql = @sql + 'AND SYNC_PNC_APPLICATION_VERSION IN (' + @application_version + ')'
	if (@emails is not null and @emails != '') 
		SET @sql = @sql + 'AND SYNC_PNC_EMAIL IN (' + @emails + ')'
	if (@devices is not null and @devices != '') 
		set @sql = @sql + 'AND SYNC_PNC_DEVICE_CODE IN (' + @devices + ')'
	set @sql = @sql + 'ORDER BY SYNC_PNC_OS_CODE, SYNC_PNC_APPLICATION_CODE'

    execute sp_executesql @sql
GO

CREATE PROCEDURE SELECT_PUSH_NOTIFICATIONS
AS
  -- Creating temp table
  set nocount on
  if object_id('tempdb..#push_list') is not null drop table #push_list
  create table #push_list(
    notification_id		INT,
	message_text	  	VARCHAR(512),
	badge_number	  	INT,
	sound_name	  		VARCHAR(256), 
	event_code	  		VARCHAR(29),  
	custom_parameters	VARCHAR(512)
  )
	begin tran
  	  -- Copy notifications to archive 
	   INSERT INTO SYNC_PUSH_NOTIFICATIONS_ARCHIVE
		(SYNC_PNA_ID,
		SYNC_PNC_ID,
		SYNC_PNA_MESSAGE_TEXT,
		SYNC_PN_PARAMETERS,
		SYNC_PNA_BADGE_NUMBER,
		SYNC_PNA_SOUND_NAME,
		SYNC_PNA_EVENT_CODE,
		SYNC_PNA_PUSH_DATE,
		SYNC_PNA_LOCK_TIME,
		SYNC_PNA_NOTIFY_TIME) 
	   SELECT 
		SYNC_PN_ID,
		SYNC_PNC_ID,
		SYNC_PN_MESSAGE_TEXT,
		SYNC_PN_PARAMETERS,
		SYNC_PN_BADGE_NUMBER,
		SYNC_PN_SOUND_NAME,
		SYNC_PN_EVENT_CODE,
		SYNC_PN_PUSH_DATE,
		SYNC_PN_LOCK_TIME,
		SYNC_PN_NOTIFY_TIME
		FROM SYNC_PUSH_NOTIFICATIONS WHERE SYNC_PN_NOTIFY_TIME IS NOT NULL
   
	  -- delete notifications copied to archive
	  DELETE FROM SYNC_PUSH_NOTIFICATIONS WHERE SYNC_PN_ID IN (SELECT SYNC_PNA_ID FROM SYNC_PUSH_NOTIFICATIONS_ARCHIVE)
	commit  
	  
	  -- Select notifications
	  INSERT INTO #push_list(notification_id,message_text,badge_number,sound_name,event_code,custom_parameters)
	  select 
		N.SYNC_PN_ID,
		N.SYNC_PN_MESSAGE_TEXT,
		N.SYNC_PN_BADGE_NUMBER,
		N.SYNC_PN_SOUND_NAME, 
		N.SYNC_PN_EVENT_CODE,
		N.SYNC_PN_PARAMETERS
	   FROM 
		 SYNC_PUSH_NOTIFICATIONS N
		WHERE 
		 (N.SYNC_PN_PUSH_DATE < getdate()) AND (N.SYNC_PN_LOCK_TIME IS NULL OR N.SYNC_PN_LOCK_TIME < dateadd(second,-300,getdate()))

 
	  -- Mark notifications
	  UPDATE SYNC_PUSH_NOTIFICATIONS SET SYNC_PN_LOCK_TIME = getdate() 
	   WHERE SYNC_PN_ID IN (SELECT notification_id from #push_list)
 
	  -- select resulted notifications
	  select notification_id,message_text,badge_number,sound_name,event_code,custom_parameters from #push_list
 GO
 
CREATE PROCEDURE SEND_NOTIFICATION 
	@notification_id int
AS
	UPDATE SYNC_PUSH_NOTIFICATIONS SET SYNC_PN_NOTIFY_TIME = getdate() WHERE SYNC_PN_ID = @notification_id
GO

CREATE PROCEDURE INSERT_PUSH_NOTIFICATIONS_CLIENT
  @os_code  			VARCHAR(256),
  @application_code  	VARCHAR(256),
  @application_version	VARCHAR(256),
  @email		  		VARCHAR(256),
  @device_code			VARCHAR(256),
  @device_name			VARCHAR(256),
  @apple_token 			VARCHAR(256)
AS
 begin tran
	 DELETE 
		FROM SYNC_PUSH_NOTIFICATIONS_CLIENTS 
	 WHERE 
		SYNC_PNC_OS_CODE = @os_code AND
		SYNC_PNC_APPLICATION_CODE = @application_code AND
		SYNC_PNC_APPLICATION_VERSION = @application_version AND
		SYNC_PNC_EMAIL = @email AND
		SYNC_PNC_DEVICE_CODE = @device_code

	 INSERT INTO SYNC_PUSH_NOTIFICATIONS_CLIENTS(SYNC_PNC_OS_CODE, SYNC_PNC_APPLICATION_CODE, SYNC_PNC_APPLICATION_VERSION, SYNC_PNC_EMAIL, SYNC_PNC_DEVICE_NAME,SYNC_PNC_DEVICE_CODE, SYNC_PNC_APPLE_TOKEN) 
	 values  (@os_code,@application_code,@application_version,@email,@device_name,@device_code,@apple_token)
 commit
GO

-- Get operations system codes
CREATE PROCEDURE GET_OS_CODES
AS
	SELECT DISTINCT SYNC_PNC_OS_CODE ITEM_CODE FROM SYNC_PUSH_NOTIFICATIONS_CLIENTS
GO

-- get applications by os code
CREATE PROCEDURE GET_APPLICATIONS
	@os_code varchar(256)
AS
	SELECT DISTINCT SYNC_PNC_APPLICATION_CODE ITEM_CODE FROM SYNC_PUSH_NOTIFICATIONS_CLIENTS WHERE SYNC_PNC_OS_CODE = @os_code
GO

-- get application versions by os code and app_code
CREATE PROCEDURE GET_APPLICATION_VERSIONS
	@os_code varchar(256),
	@application_code varchar(256)
AS
	SELECT DISTINCT SYNC_PNC_APPLICATION_VERSION ITEM_CODE FROM SYNC_PUSH_NOTIFICATIONS_CLIENTS WHERE SYNC_PNC_OS_CODE = @os_code AND SYNC_PNC_APPLICATION_CODE = @application_code
GO

CREATE PROCEDURE GET_EMAILS
	@email varchar(256)
AS
	SELECT DISTINCT SYNC_PNC_EMAIL ITEM_CODE FROM SYNC_PUSH_NOTIFICATIONS_CLIENTS
GO

CREATE PROCEDURE GET_DEVICES
	@email varchar(8000)
AS
    SET NOCOUNT ON;
    declare @sql nvarchar(MAX)

    set @sql = 'SELECT DISTINCT SYNC_PNC_DEVICE_NAME ITEM_NAME,SYNC_PNC_DEVICE_CODE ITEM_CODE FROM SYNC_PUSH_NOTIFICATIONS_CLIENTS WHERE SYNC_PNC_EMAIL in (' + @email + ')'
    execute sp_executesql @sql
GO

CREATE PROCEDURE SET_NOTIFICATION_2_CLIENT_STATUS
	@pnid INT,
	@pnc_token varchar(128),
	@status INT
AS
	update SYNC_PUSH_NOTIFICATIONS2CLIENT set SYNC_PNC_STATUS = @status WHERE SYNC_PN_ID = @pnid AND SYNC_PNC_ID = (SELECT top 1 SYNC_PNC_ID FROM SYNC_PUSH_NOTIFICATIONS_CLIENTS WHERE SYNC_PNC_APPLE_TOKEN = @pnc_token)
GO

CREATE PROCEDURE GET_NOTIFICATIONS
	@from INT,
	@count INT
AS
	SELECT * FROM (
		SELECT [RANK] = ROW_NUMBER() OVER (ORDER BY SYNC_PNA_ID DESC), SYNC_PNA_ID, SYNC_PNA_MESSAGE_TEXT,SYNC_PNA_NOTIFY_TIME FROM SYNC_PUSH_NOTIFICATIONS_ARCHIVE
	) A	WHERE A.[RANK] BETWEEN @from+1 AND @from+@count	
GO
