DECLARE @BASE VARCHAR(50)
SET @BASE = 'MIS_NAVIGATOR_DATA'
IF DB_ID(@BASE) is not null BEGIN
  exec ('
	USE ' + @BASE + '
	GRANT EXECUTE ON [MIS_NAVIGATOR_DATA].[dbo].[p_GetPDFDocumentMobile] 					TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_NAVIGATOR_DATA].[dbo].[p_GetPDFListMobile] 						TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_NAVIGATOR_DATA].[dbo].[PUB_NAV_DATA_DOCS] 						TO [IPAD_PROXY_USER]
	PRINT ''' + @BASE + ': user granted''
  ')
END
ELSE
	PRINT @BASE + ' does not exists'
GO

DECLARE @BASE VARCHAR(50)
SET @BASE = 'MIS_PCA_DKK_DATA'
IF DB_ID(@BASE) is not null BEGIN
  exec ('
	USE ' + @BASE + '
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[t_100_002_Report_Periods] 					TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[t_100_004_Report_Territories] 				TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[t_100_005_Report_Currencies] 				TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[t_100_009_000_Report_Clients] 				TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[t_100_010_Report_Benefits] 					TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[t_100_011_Report_Holdings] 					TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[t_200_001_DM_Currency_Showing_Table] 		TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[t_300_001_DM_Fact_Data] 						TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[t_300_005_DM_Indicators] 					TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[v_100_003_Report_Branches_DM] 				TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[v_300_003_DM_Rates_Data] 					TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[v_300_004_DM_Exchange_Data] 					TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_PCA_DKK_DATA].[dbo].[v_300_006_Markets_Indexes] 					TO [IPAD_PROXY_USER]
  ')
END
ELSE
	PRINT @BASE + ' does not exists'
GO

DECLARE @BASE VARCHAR(50)
SET @BASE = 'MIS_PCA_CIB_DYNAMIC_MODEL'
IF DB_ID(@BASE) is not null BEGIN
  exec ('
	USE ' + @BASE + '
	GRANT SELECT  ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[t_000_Report_Columns_Structure] 				TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[getData_XML] 						TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[p_getBranches_FilterXML] 			TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[p_getCorrectionsConstants_FilterXML]TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[p_getCurrency_FilterXML] 			TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[p_getDepartments_FilterXML] 		TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[p_getDimension_FilterXML] 			TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[p_getExchangeIndexes_FilterXML] 	TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[p_getHierarchy] 					TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[p_getPeriods_FilterXML] 			TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_PCA_CIB_DYNAMIC_MODEL].[dbo].[f_FormatValue] 						TO [IPAD_PROXY_USER]
	PRINT ''' + @BASE + ': user granted''
  ')
END
ELSE
	PRINT @BASE + ' does not exists'
GO

DECLARE @BASE VARCHAR(50)
SET @BASE = 'MIS_BASE2'
IF DB_ID(@BASE) is not null BEGIN
  exec ('
	USE ' + @BASE + '
	GRANT SELECT  ON [MIS_BASE2].[dbo].[_tAccessObject2Role] 								TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_BASE2].[dbo].[_tAccessObject] 									TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_BASE2].[dbo].[_tRole2User] 										TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_BASE2].[dbo].[_tRole] 											TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_BASE2].[dbo].[_tTerbank] 											TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_BASE2].[dbo].[_tUser] 											TO [IPAD_PROXY_USER]
	PRINT ''' + @BASE + ': user granted''
  ')
END
ELSE
	PRINT @BASE + ' does not exists'
GO


DECLARE @BASE VARCHAR(50)
SET @BASE = 'MIS_RUBRICATOR'
IF DB_ID(@BASE) is not null BEGIN
  exec ('
	USE ' + @BASE + '
	GRANT EXECUTE ON [MIS_RUBRICATOR].[dbo].[getChangeAfterId] 								TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_RUBRICATOR].[dbo].[groupListMobile] 								TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_RUBRICATOR].[dbo].[logoListMobile] 								TO [IPAD_PROXY_USER]
	GRANT EXECUTE ON [MIS_RUBRICATOR].[dbo].[reportListMobileTB] 							TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[changelog] 									TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[default_params] 								TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[group] 										TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[group_report] 									TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[group_resource] 								TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[groupList] 									TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[obj_tag] 										TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[report] 										TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[report_resource] 								TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[report_type] 									TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[reportList] 									TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[resource] 										TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RUBRICATOR].[dbo].[resource_type] 								TO [IPAD_PROXY_USER]
	PRINT ''' + @BASE + ': user granted''
  ')
END
ELSE
	PRINT @BASE + ' does not exists'
GO

DECLARE @BASE VARCHAR(50)
SET @BASE = 'MIS_RETAIL_VSP_MOBILE'
IF DB_ID(@BASE) is not null BEGIN
  exec ('
	USE ' + @BASE + '
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DIC_BAL_INDICATOR] 						TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DIC_BANK_T] 							TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DIC_PL_INDICATOR] 						TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DIC_PRODUCT] 							TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DIC_REPORT_DATE] 						TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DIC_SALE_INDICATOR] 					TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DTA_BALANCE_PRODUCT_T] 					TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DTA_BALANCE_T] 							TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DTA_PL_PRODUCT_T] 						TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DTA_PL_T] 								TO [IPAD_PROXY_USER]
	GRANT SELECT  ON [MIS_RETAIL_VSP_MOBILE].[dbo].[DTA_SALE_T] 							TO [IPAD_PROXY_USER]
	PRINT ''' + @BASE + ': user granted''
  ')
END
ELSE
	PRINT @BASE + ' does not exists'
GO