USE MIS_NAVIGATOR_KPI_20
GO
GRANT EXECUTE ON dbo.getDataPeriods TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON dbo.getDataPointNames TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON dbo.getTextLang TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON dbo.ObrDate TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON dbo.SetNull TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_AddEmployee TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_addNewReportSet TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_addNewUserDashBoard TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_changeComment TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getComment TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoard TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardData TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardDataCardDetail TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardDataCardRespUser TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardDataDomain TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardDataFA TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardDataGrid TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardDataReport TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardDataSearch TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardDataTree TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardDataTreeOldWay TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardTypeByID TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getEnterPointData TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getLastModifyDate TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getMyDashBoardID TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getReportDataByID TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getResourceDataByID TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getUserNotification TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_ParseInputParameters TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_checkAccessToDashBoard TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_ConvertMeasure TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_formatDate TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_formatValue TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_get4Q TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getChangeRate TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getDashBoard2 TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getDeviation TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getEmployeeByEmail TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getEmployeeByIP TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getHasComment TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getIndicatorPrognoz TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getIsEdit TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getIsKPI TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getLinkCard TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getMyDashBoardID TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getPrognoz TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getRate TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getTextLanguage TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.getCardData TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.getGridKPIValue TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.getGridKPIValue3 TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getGridKPIValue4 TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.fn_getOpenObjectLink TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.getKTItype TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.makeLog20 TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_addNewUserDashBoard TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_changeComment TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getComment TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getDashBoard TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getDashBoardData TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getDashBoardDataCardDetail TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getDashBoardDataFA TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getDashBoardDataSearch TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getEnterPointData TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getLastModifyDate TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getMyDashBoardID TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getReportDataByID TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getResouceImageByID TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.mobile_getUserNotification TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_addNewUserDashBoard TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_changeComment TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_getComment TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_getDashBoard TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_getDashBoardData TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_getDashBoardDataCardDetail TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_getDashBoardDataFA TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_getDashBoardDataSearch TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_getEnterPointData TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_getReportDataByID TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.portal_getResourceDataByID TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON TYPE::UI.tpInputParameters TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.Calendar_VW TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.getDATA_POINT_IDs TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.key_words TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.MultyLangWords TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NAV_KPI_ARROW_POINT TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NAV_KPI_CARD TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NAV_KPI_DASHBOARD TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NAV_KPI_DASHBOARD_DEFAULT_PARAMS TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NAV_KPI_DASHBOARD_DEFAULT_PARAMS_VW TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NAV_KPI_FA_POK TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NAV_KPI_FA_POK_CHILD TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NAV_KPI_TREE_ARROW TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NAV_KPI_TREE_CARDS TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NEW_DataPoint_VW TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.NEW_PUB_NAV_DATA_VW TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.PUB_NAV_AXISDETAIL_VW TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.PUB_NAV_KPI_POK_VW TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.PUB_NAV_KPI_POKS TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.PUB_NAV_KPI_POKS_VW TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.PUB_NAV_MEASURE_VW TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.fn_getHierarchyRole TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.ParamsLog TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tBusinessRole TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tBusinessRoleDashBoard TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tBusinessRoleEnterPoint TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tBusinessRoleToEmployee TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tCalendar TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tCard TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tCardIndicator TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tComment TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tCorrectionKPI TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tDashBoard TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tDashBoardDomain TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tDashBoardDomainCard TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tdicCorrectionType TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tDomain TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tEmployee TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tEmployeeResponsible TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tEnterPoint TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tGrid TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tLink TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tLinkCard TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tLinkReport TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tLinkToolBar TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tMultiLanguageWord TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tPage TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tPageLink TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tPushNotification TO IPAD_PROXY_USER
GO
GRANT UPDATE ON UI.tPushNotificationStateLog TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tPushNotificationReadLog TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tPushNotificationStateLog TO IPAD_PROXY_USER
GO
GRANT INSERT ON UI.tPushNotificationStateLog TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tReport TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tReportDocument TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tReportSet TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tResourceImage TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.tToolBar TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_BusinessRole TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_BusinessRoleDashBoard TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_BusinessRoleToEmployee TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_Calendar TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_Card TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_CardIndicator TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_DashBoard TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_DashBoardDomain TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_DashBoardDomainCard TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_Domain TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_Employee TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_EmployeeResponsible TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_EnterPoint TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_Grid TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_Indicator TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_LinkToolBar TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_Measure TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_MultiLanguageWord TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_Page TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_PageLink TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_ReportDocument TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_ResourceImage TO IPAD_PROXY_USER
GO
GRANT SELECT  ON UI.v_ToolBar TO IPAD_PROXY_USER 
GO
GRANT EXECUTE ON UI.mobile_getDashBoardDataSearch TO IPAD_PROXY_USER
GO

grant select on UI.tdicPokLinkType to IPAD_PROXY_USER
GO
grant select on UI.tPokLink to IPAD_PROXY_USER
GO
grant select on UI.tPokLinkDetail to IPAD_PROXY_USER
GO
GRANT EXECUTE on [dbo].[SELECT_NOTIFICATIONS_FOR_MONITOR] TO IPAD_PROXY_USER
go
GRANT EXECUTE on [dbo].[SELECT_NOTIFICATIONS_FOR_SEND] TO IPAD_PROXY_USER
go
GRANT EXECUTE on [dbo].[SELECT_USER_NOTIFICATION] TO IPAD_PROXY_USER
GO
GRANT EXECUTE on [dbo].[SELECT_NOTIFICATION_HISTORY] TO IPAD_PROXY_USER
GO
GRANT EXECUTE on [dbo].[UPDATE_NOTIFICATION_READ_STATUS] TO IPAD_PROXY_USER
GO
GRANT EXECUTE on [dbo].[UPDATE_NOTIFICATION_SEND_STATUS] TO IPAD_PROXY_USER
GO
GRANT EXECUTE on [dbo].[SELECT_USER_VIEWED_NOTIFICATION] TO IPAD_PROXY_USER
GO
GRANT SELECT  ON dbo.[getAllAxisDetail2] TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.getGridKPIValue2 TO IPAD_PROXY_USER
GO
GRANT EXECUTE ON UI.core_getDashBoardDataKPIPPR TO IPAD_PROXY_USER
GO
GRANT SELECT ON [dbo].[preobr_str_to_tab] TO IPAD_PROXY_USER
--GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI.tTableOrder TO IPAD_PROXY_USER
GO

--GRANT EXECUTE ON MIS_NAVIGATOR_KPI_20.UI2.core_generateGroupCardID TO IPAD_PROXY_USER 
--GO
--GRANT EXECUTE ON MIS_NAVIGATOR_KPI_20.UI2.core_PublishDashBoardSettings TO IPAD_PROXY_USER 
--GO
--GRANT EXECUTE ON MIS_NAVIGATOR_KPI_20.UI2.core_putCustomActions TO IPAD_PROXY_USER 
--GO
--GRANT EXECUTE ON MIS_NAVIGATOR_KPI_20.UI2.core_putDasboardSettings TO IPAD_PROXY_USER 
--GO
--GRANT EXECUTE ON MIS_NAVIGATOR_KPI_20.UI2.mobile_putDasboardSettings TO IPAD_PROXY_USER 
--GO
--GRANT EXECUTE ON MIS_NAVIGATOR_KPI_20.UI2.portal_putDasboardSettings TO IPAD_PROXY_USER 
--GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tObject TO IPAD_PROXY_USER 
GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tPersonalDashBoard TO IPAD_PROXY_USER 
--GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_BusinessRoleDashBoard TO IPAD_PROXY_USER 
--GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_BusinessRolePosition TO IPAD_PROXY_USER 
GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_CustomAction TO IPAD_PROXY_USER 
--GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_DashBoardDomain TO IPAD_PROXY_USER 
--GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_DashBoardDomainCard TO IPAD_PROXY_USER 
--GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_EmployeeOrganizationPosition TO IPAD_PROXY_USER 
GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tCustomAction TO IPAD_PROXY_USER 
--GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tCustomCardOrder TO IPAD_PROXY_USER 
--GO
--GRANT EXECUTE ON MIS_NAVIGATOR_KPI_20.UI2.fn_getEmployeeByEmail TO IPAD_PROXY_USER 
--GO
--GRANT EXECUTE ON MIS_NAVIGATOR_KPI_20.UI2.fn_getEmployeeByIP TO IPAD_PROXY_USER 
--GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_Card TO IPAD_PROXY_USER 
--GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tBusinessRolePosition TO IPAD_PROXY_USER 
GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tDashBoardDomainCard TO IPAD_PROXY_USER 
--GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tEmployeeOrganizationPosition TO IPAD_PROXY_USER 
GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_ManagmentStructure TO IPAD_PROXY_USER 
GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_OrganizationPosition TO IPAD_PROXY_USER 
GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_EmployeeUser_map TO IPAD_PROXY_USER 
--GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_User TO IPAD_PROXY_USER 
--GO
--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tCard TO IPAD_PROXY_USER 
--GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.v_Relation TO IPAD_PROXY_USER 
GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tManagmentStructure TO IPAD_PROXY_USER 
GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tOrganizationPosition TO IPAD_PROXY_USER 
GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tEmployeeUser_map TO IPAD_PROXY_USER 
GO
GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tRelation TO IPAD_PROXY_USER 
GO
GRANT SELECT ON UI2.fn_getPrognoz TO IPAD_PROXY_USER
GO

--GRANT SELECT ON MIS_NAVIGATOR_KPI_20.UI2.tTableOrder TO IPAD_PROXY_USER
--GO
GRANT EXECUTE ON [UI].[fn_getResponsible] TO IPAD_PROXY_USER
GO

USE MIS_BASE2
GO
GRANT SELECT ON dbo._tUser TO IPAD_PROXY_USER 
GO


USE MIS_NAVIGATOR_DATA_20
GO
GRANT SELECT ON dbo.NEW_DataPoint TO IPAD_PROXY_USER 
GO
GRANT SELECT ON dbo.NEW_PUB_NAV_DATA TO IPAD_PROXY_USER 
GO
GRANT SELECT ON dbo.parse_str_to_token TO IPAD_PROXY_USER 
GO
GRANT SELECT ON dbo.preobr_str_to_tab TO IPAD_PROXY_USER 
GO
GRANT SELECT ON dbo.PUB_NAV_AXISDETAIL TO IPAD_PROXY_USER 
GO
GRANT SELECT ON dbo.PUB_NAV_KPI_POK TO IPAD_PROXY_USER 
GO
GRANT SELECT ON dbo.PUB_NAV_Measure TO IPAD_PROXY_USER 
GO

grant select on tdicPokGroup to IPAD_PROXY_USER
GO
