
IF OBJECT_ID('SYNC_CONFIG') IS NOT NULL DROP TABLE SYNC_CONFIG
GO
CREATE TABLE SYNC_CONFIG(
   PROPERTY_KEY    VARCHAR(256) PRIMARY KEY,
   PROPERTY_VALUE  VARCHAR(1024) NOT NULL,
   PROPERTY_DESC   VARCHAR(1024)
)
GO
INSERT INTO SYNC_CONFIG VALUES('IS_DB_LOGGING_ENABLED','true','Enables or disables logging to the database')
GO
