IF OBJECT_ID('SQL_TEMPLATES_SERVER', N'U') is not null drop table SQL_TEMPLATES_SERVER
GO
CREATE TABLE SQL_TEMPLATES_SERVER(
  TEMPLATE_CODE varchar(900) primary key,
  TEMPLATE_SQL  varchar(max)  null,
  TEMPLATE_DESC  varchar(500)  null,
)
GO 

IF OBJECT_ID('SQL_TEMPLATES_MOBILE') is null
CREATE TABLE SQL_TEMPLATES_MOBILE(
  TEMPLATE_CODE varchar(900) primary key,
  TEMPLATE_SQL  varchar(max)  null,
  APP_CODE  varchar(50)  null
)

GO
IF OBJECT_ID('SQL_TEMPLATES', N'U') is not null drop table SQL_TEMPLATES
GO

IF OBJECT_ID('SQL_TEMPLATES', N'V') is not null drop view SQL_TEMPLATES
GO

CREATE VIEW SQL_TEMPLATES AS 
select TEMPLATE_CODE,TEMPLATE_SQL from SQL_TEMPLATES_SERVER
union all
select TEMPLATE_CODE,TEMPLATE_SQL from SQL_TEMPLATES_MOBILE
GO

INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('SYNCSERVER.IS_ALLOWED_TO_USE_APP','exec @ALPHA_SOURCE_DB@.dbo.SP_IS_ALLOWED_TO_USE_APP ? , ?, ?','This template does not write anything. Only checks that user email has access to application.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('SYNCSERVER.IS_ALLOWED_TO_DOWNLOAD_FILE','exec @ALPHA_SOURCE_DB@.dbo.SP_IS_ALLOWED_TO_DOWNLOAD_FILE ? ,? ,?, ?','This template does not write anything. Only checks that user email has access to download file.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('SYNCSERVER.LOG_SQL','exec @ALPHA_GENERATOR_DB@.dbo.SP_SYNC_STORE_LOGMSG_WITH_ID ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?','This template write a record to SYNC_LOGS table.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('SYNCSERVER.DP_NOT_DEL_FILE_MOV_NOTIFICATION','exec @ALPHA_MONITOR_DB@..SP_DEL_FILE_MOV_NOTIFICATION ?,?,?','This template deletes record about not delivered file ( table NOTIFICATION in monitor DB) when file succesfully delivered to SIGMA.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('SYNCSERVER.DP_NOT_ADD_ERROR','exec @ALPHA_MONITOR_DB@..SP_ADD_ERROR ?,?,?','This template add record about error situation (table NOTIFICATIONS in monitor db)')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('SYNCSERVER.DP_NOT_PING','exec @ALPHA_MONITOR_DB@..SP_PING ?,?','This template updates record in (table NOTIFICATION_SERVERS in monitor DB) - sets last ping datetime from server.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('SYNCSERVER.SINGLE_FILES_REQUEST_STATUS','exec @ALPHA_GENERATOR_DB@..SP_GET_FILE_STATUSES','This template does not write anything. It selects records from SYNC_CACHE_STATIC_FILES table')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('SYNCSERVER.GENERATOR_USER_GROUP_DRAFT','exec @ALPHA_GENERATOR_DB@..SP_GET_GENERATOR_USER_GROUPS_FOR_DRAFT','This template does not write anything. It selects records from GENERATOR_GROUP_USERS table')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('SYNCSERVER.ADD_GENERATOR_STATE','exec @ALPHA_GENERATOR_DB@..SP_SYNC_STATIC_FILES_GEN_ADD_STATE ?,?,?,?,?,?','This templates adds notification signal to alpha about file is succesfully or not succesfully loaded to sigma.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('TEST.TEST','select getdate(), @@servername, db_name()','This template for test, returns information about sql server')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('SELECT 1','SELECT 1','This template for test, returns 1 from sql server')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('MIS_BASE2.UPDATE_USER','exec @ALPHA_SOURCE_DB@.dbo.SP_MIS_BASE2_UPDATE_USER ?,?,?,?,?,?,?,?,?,?','This template insert/update user in mis_base2 structure.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('MIS_BASE2.UPDATE_USER_ROLES','exec @ALPHA_SOURCE_DB@.dbo.SP_MIS_BASE2_UPDATE_USER_ROLES ?,?,?','This templates delete/added roles to user in mis_base2 structure.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('MIS_BASE2.GET_USER_ROLES','exec @ALPHA_SOURCE_DB@.dbo.SP_MIS_BASE2_GET_USER_ROLES ?','This templates returns user role list in mis_base2 structure.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('MIS_BASE2.GET_INAV_ROLES','exec @ALPHA_SOURCE_DB@.dbo.SP_MIS_BASE2_GET_INAV_ROLES','This template returns all navigator roles in mis_base2 structure.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('MIS_BASE2.GET_USERS_LIST','exec @ALPHA_SOURCE_DB@.dbo.SP_MIS_BASE2_GET_USERS_LIST ?,?,?,?,?,?','This templates search users in mis_base2 structure.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('MIS_BASE2.GET_USER_INFO','exec @ALPHA_SOURCE_DB@.dbo.SP_MIS_BASE2_GET_USER_INFO ?','This template select user info in mis_base2 structure.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('MIS_BASE2.GET_DICTIONARY_TERRBANKS','exec @ALPHA_SOURCE_DB@.dbo.SP_MIS_BASE2_GET_TERRBANKS','This template return dictionary terrbanks in mis_base2 structure.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('MIS_BASE2.GET_DICTIONARY_UNITS','exec @ALPHA_SOURCE_DB@.dbo.SP_MIS_BASE2_GET_UNITS','This template return dictionary units in mis_base2 structure.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('MIS_BASE2.GET_DICTIONARY_BLOCKS','exec @ALPHA_SOURCE_DB@.dbo.SP_MIS_BASE2_GET_BLOCKS','This template return dictionary blocks in mis_base2 structure.')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('INAVIGATOR20.GET_NOTIFICATIONS_FOR_SEND','exec @ALPHA_SOURCE_DB@.dbo.SELECT_NOTIFICATIONS_FOR_SEND','This template returns push notifications for send')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('INAVIGATOR20.UPDATE_NOTIFICATION_SEND_STATUS','exec @ALPHA_SOURCE_DB@.dbo.UPDATE_NOTIFICATION_SEND_STATUS ?,?,?','This template updates push notification send status')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('INAVIGATOR20.GET_NOTIFICATIONS_FOR_MONITOR','exec @ALPHA_SOURCE_DB@.dbo.SELECT_NOTIFICATIONS_FOR_MONITOR','This template returns push notifications for monitor')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('INAVIGATOR20.SELECT_NOTIFICATION_HISTORY','exec @ALPHA_SOURCE_DB@.dbo.SELECT_NOTIFICATION_HISTORY ?','This template returns push notification statuses history')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('INAVIGATOR20.TEST.GET_NOTIFICATIONS_FOR_SEND','exec @ALPHA_SOURCE_DB@.dbo.SELECT_NOTIFICATIONS_FOR_SEND 1','This TEST template returns push notifications for send')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('INAVIGATOR20.TEST.UPDATE_NOTIFICATION_SEND_STATUS','exec @ALPHA_SOURCE_DB@.dbo.UPDATE_NOTIFICATION_SEND_STATUS ?,?,?,1','This TEST template updates push notification send status')
INSERT INTO SQL_TEMPLATES_SERVER (TEMPLATE_CODE,TEMPLATE_SQL,TEMPLATE_DESC) VALUES ('PORTAL.DASHBOARD_DATA_SEARCH','EXEC [MIS_NAVIGATOR_KPI_20].[UI].[portal_getDashBoardDataSearch] ?','Процедура поиска для портального приложения')
GO

INSERT SQL_TEMPLATES_MOBILE (TEMPLATE_CODE, TEMPLATE_SQL) VALUES (N'IRUBRICATOR.MIS_RUBRICATOR.GROUP_LIST_MOBILE', N'exec MIS_RUBRICATOR.dbo.groupListMobile ?, ?, ?')
INSERT SQL_TEMPLATES_MOBILE (TEMPLATE_CODE, TEMPLATE_SQL) VALUES (N'IRUBRICATOR.MIS_RUBRICATOR.REPORT_LIST_MOBILE_TB', N'exec MIS_RUBRICATOR.dbo.reportListMobileTB ?, ?, ?')
GO

IF OBJECT_ID('SUBST_DICT') is not null drop table SUBST_DICT
GO
CREATE TABLE SUBST_DICT (
  SUBST_CODE varchar(50) primary key,
  SUBST_VALUE varchar(MAX)  null,
  SUBST_DESC varchar(50) null,
  APP_CODE varchar(50)  null
)
GO 
