use [syncserver]
go
set nocount on
go
IF OBJECT_ID('SYNC_CONFIG') IS NOT NULL DROP TABLE SYNC_CONFIG
GO

CREATE TABLE SYNC_CONFIG(
   PROPERTY_KEY    VARCHAR(256)  NOT NULL,
   PROPERTY_VALUE  VARCHAR(1024) NOT NULL,
   PROPERTY_DESC   VARCHAR(1024)     NULL
)
GO
SET NOCOUNT ON

INSERT INTO SYNC_CONFIG VALUES('PARAMETER','VALUE','DESCRIPTION')

GO
